theme: jekyll-theme-minimal
title: Data Analytics Portfolio
description: >
  A portfolio of my data analytics projects, that i have made through out my learning journey. <br />
  In each project overview, a description of the project and the most important results are given. <br />
  The titles are links to the coresponding github repositories, where the code and more in depth explanations lie. <br />
  Commen projects i will do include, data analysis in python, R-studio and Excel and data querying in SQL. <br />
  More creative projects with different purposes will also be found in the projects list.
